//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animal
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> idState { get; set; }
        public Nullable<int> patas { get; set; }
        public byte[] picture { get; set; }
    }
}
